=== renanzulian/java-web/xml-project/src/format.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="Sales">
        <complexType>
            <sequence>
                <element name="Products">
                    <complexType>
                        <sequence>
                            <element name="Product" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="Name" type="string"/>
                                        <element name="Price" type="double"/>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="currency"/>
        </complexType>
    </element>

</schema>

=== renanzulian/java-web/xml-project/src/sales.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Sales currency="BRL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="format.xsd">
    <Products>
        <Product>
            <Name>Java EE Course</Name>
            <Price>19.90</Price>
        </Product>
        <Product>
            <Name>Dell XPS 15'</Name>
            <Price>1299.00</Price>
        </Product>
        <Product>
            <Name>Logitech Master 3</Name>
            <Price>99.90</Price>
        </Product>
    </Products>
</Sales>
